site_name: Summer Project
repo_url: https://github.com/ARU300/SummerProject
site_description: A school Summer Project. Uses LSTM, LR and SVM models in Python to predict the stocks for a specificied company. An Flask API is also included.
site_author: ARU300
copyright: GNU General Public License v3.0
nav:
    - Home: README.md
    - 'Issue Tracker': 'https://github.com/ARU300/SummerProject/issues'